export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

// Twitter
export const TWITTER_LIST_REQUEST = 'YOUTUBE_LIST_REQUEST'
export const TWITTER_LIST_SUCCESS = 'YOUTUBE_LIST_SUCCESS'
export const TWITTER_LIST_FAIL = 'TWIYOUTUBEST_FAIL'
export const TWITTER_LIST_RESET = 'TWYOUTUBEIST_RESET'

export const YOUTUBE_LIST_REQUEST = 'YOUTUBE_LIST_REQUEST'
export const YOUTUBE_LIST_SUCCESS = 'YOUTUBE_LIST_SUCCESS'
export const YOUTUBE_LIST_FAIL = 'TWIYOUTUBEST_FAIL'
export const YOUTUBE_LIST_RESET = 'TWYOUTUBEIST_RESET'


export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST'
export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS'
export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL'
export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET'